[package]
name = "ricochet_solver"
version = "0.1.0"
authors = ["Carl Scherer"]
edition = "2018"

[dependencies]
ricochet_board = { path = "../ricochet_board" }
fnv = "1.0.7"

[dev-dependencies]
rand = "0.7.3"
rayon = "1.5.0"
itertools = "0.9.0"
chrono = "0.4.19"
