[package]
name = "ricochet_solver"
version = "0.1.0"
authors = ["carl"]

[dependencies]
ricochet_board = { path = "../ricochet_board" }
rustc-serialize = "0.3"

[profile.test]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
