[package]
name = "ricochet_board"
version = "0.1.0"
authors = ["Carl Scherer"]
edition = "2018"

[dependencies]
itertools = "0.10.0"

# [lib]
# name = "ricochet_board"
# crate-type = ["rlib", "cdylib"]

# [dependencies]
# pyo3 = { version = "0.13.0", features = ["extension-module"] }
